# Generated by Django 5.1.4 on 2025-01-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('non_active', 'Non Active'), ('terminated', 'Terminated'), ('graduate', 'Graduate')], default='active', max_length=20),
        ),
    ]
