# Generated by Django 5.1.4 on 2025-01-05 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0004_alter_bed_status'),
        ('students', '0005_alter_student_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='room',
        ),
        migrations.RemoveField(
            model_name='student',
            name='room_zone',
        ),
        migrations.AddField(
            model_name='student',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostels.bed'),
        ),
    ]
