# Generated by Django 5.1.4 on 2025-01-05 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0006_bed_bed_number'),
        ('students', '0008_remove_student_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='hostels.bed'),
        ),
    ]
