# Generated by Django 5.1.4 on 2025-01-05 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_bed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='bed',
        ),
    ]
