# Generated by Django 5.1.6 on 2025-07-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('foundation', 'Foundation'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('terminated', 'Terminated'), ('internship', 'Internship')], default='active', max_length=20),
        ),
    ]
