# Generated by Django 5.1.4 on 2025-01-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('under-maintenance', 'Under Maintenance')], default='available', max_length=20),
        ),
    ]
