# Generated by Django 5.1.4 on 2025-01-04 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0003_remove_room_status_bed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bed',
        ),
    ]
