# Generated by Django 5.1.4 on 2025-01-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0004_alter_bed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('under_maintenance', 'Under Maintenance')], default='available', max_length=20),
        ),
    ]
