# Generated by Django 5.1.4 on 2025-01-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0005_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='bed_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
