# Generated by Django 5.1.4 on 2024-12-19 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRoomRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('supporting_doc', models.FileField(upload_to='change_room_docs/')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_room_requests', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('issue', models.CharField(max_length=255)),
                ('occurrence', models.CharField(max_length=255)),
                ('evidence_photo', models.ImageField(upload_to='maintenance_evidence/')),
                ('explanation', models.TextField()),
                ('status', models.CharField(choices=[('ppk_done', 'PPK Done'), ('rejected', 'Rejected')], max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='students.student')),
            ],
        ),
    ]
