# Generated by Django 5.1.4 on 2024-12-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='student',
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='nationality',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='student_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='evidence_photo',
            field=models.FileField(upload_to='maintenance_evidence/'),
        ),
    ]
