# Generated by Django 5.1.4 on 2024-12-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_remove_changeroomrequest_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='evidence_photo',
            field=models.FileField(default='null', upload_to='maintenance_evidence/'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('appending', 'Appending'), ('ppk_done', 'PPK Done'), ('rejected', 'Rejected')], default='appending', max_length=20),
        ),
    ]
