# Generated by Django 5.1.4 on 2024-12-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_alter_maintenancerequest_evidence_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeroomrequest',
            name='student',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='changeroomrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='appending', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ppk_done', 'PPK Done'), ('rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
