# Generated by Django 5.1.4 on 2025-01-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_maintenancerequest_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeroomrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
