# Generated by Django 5.1.6 on 2025-02-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_alter_changeroomrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ppk_done', 'PPK Done'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
