# Generated by Django 5.1.6 on 2025-07-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0008_alter_maintenancerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
